AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test-gbee

  Sample SAM Template for test-gbee

Parameters:
  NodeEnv:
    Type: String
  ServerPort:
    Type: String
  ServerHostname:
    Type: String
  DatabaseUrl:
    Type: String
  JwtSecret:
    Type: String
  DefaultUserName:
    Type: String
  DefaultUserEmail:
    Type: String
  DefaultUserPassword:
    Type: String

Globals:
  Function:
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        NODE_ENV: !Ref NodeEnv
        JWT_SECRET: !Ref JwtSecret
        SERVER_PORT: !Ref ServerPort
        SERVER_HOSTNAME: !Ref ServerHostname
        DATABASE_URL: !Ref DatabaseUrl
        DEFAULT_USER_NAME: !Ref DefaultUserName
        DEFAULT_USER_EMAIL: !Ref DefaultUserEmail
        DEFAULT_USER_PASSWORD: !Ref DefaultUserPassword

Resources:
  TestGbeeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes:
        - "*~1*"

  App:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 30
      Events:
        AppCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: TestGbeeApi
    Metadata:
      BuildMethod: esbuild

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  AppApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${TestGbeeApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
