name: Deploy SAM App

on:
  push:
    branches: [main]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install AWS SAM CLI
      uses: aws-actions/setup-sam@v2

    - name: Build the app
      run: sam build

    - name: Deploy the app
      run: |
        sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --stack-name gnest-app-stack \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --region ${{ secrets.AWS_REGION }} \
          --parameter-overrides \
            NODE_ENV=${{ secrets.NODE_ENV }} \
            SERVER_PORT=${{ secrets.SERVER_PORT }} \
            SERVER_HOSTNAME=${{ secrets.SERVER_HOSTNAME }} \
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            JWT_SECRET=${{ secrets.JWT_SECRET }} \
            DEFAULT_USER_NAME=${{ secrets.DEFAULT_USER_NAME }} \
            DEFAULT_USER_PASSWORD=${{ secrets.DEFAULT_USER_PASSWORD }} \
            DEFAULT_USER_EMAIL=${{ secrets.DEFAULT_USER_EMAIL }}
